---
- hosts: localhost
  tasks:
    - name: Add Sublime Text's GPG key
      become: yes
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present
    - name: Ensure Sublime Text's PPA repository present
      become: yes
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        filename: "sublime-text"
        state: present
    - name: Run "apt update" as a separate step
      become: yes
      apt:
        update_cache: yes
    - name: Ensure essential libraries for development are present
      become: yes
      apt:
        name: ['build-essential', 'libssl-dev', 'libffi-dev', 'python-dev', 'python3-dev', 'libgtk2.0-0']
        state: present
    - name: Ensure useful utilities are present
      become: yes
      apt:
        name: ['tmux', 'kdiff3', 'sublime-text']
        state: present
    - name: Ensure SQLite3 utilities are present
      become: yes
      apt:
        name: ['sqlite3', 'sqlitebrowser']
        state: present
    - name: Ensure Python 3 dependencies present
      become: yes
      apt:
        name: ['python3', 'python3-venv', 'virtualenvwrapper']
        state: present
    - name: Ensure Custom Hahow Python virtual environment present
      shell: "source {{ virtualenvwrapper_script }} && mkvirtualenv -r {{ requirement_file }} -p /usr/bin/python3.6 {{ venv_name }}"
      args:
        chdir: "{{ ansible_env.HOME }}"
        executable: "{{ ansible_env.SHELL }}"
        creates: "{{ virtualenvwrapper_hook_dir }}/{{ venv_name }}"
      vars:
        requirement_file: '/vagrant/provision/templates/requirements.txt'
        venv_name: 'hahow'
        virtualenvwrapper_script: '/usr/share/virtualenvwrapper/virtualenvwrapper.sh'
        virtualenvwrapper_hook_dir: "{{ ansible_env.HOME }}/.virtualenvs"
    - name: Install Git configuration
      template:
        src: templates/gitconfig.j2
        dest: /home/vagrant/.gitconfig
        owner: vagrant
        force: no
    - name: Install Vim configuration
      template:
        src: templates/vimrc
        dest: /home/vagrant/.vimrc
    - name: Ensure directory repos present
      file:
        path: '/home/vagrant/repos/python-hahow'
        state: directory
