---
- hosts: localhost
  tasks:
    - name: Add Sublime Text's GPG key
      become: yes
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present
    - name: Ensure Sublime Text's PPA repository present
      become: yes
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        filename: "sublime-text"
        state: present
    - name: Run "apt update" as a separate step
      become: yes
      apt:
        update_cache: yes
    - name: Ensure essential libraries for development are present
      become: yes
      apt:
        name: ['build-essential', 'libssl-dev', 'libffi-dev', 'python-dev']
        state: present
    - name: Ensure useful utilities are present
      become: yes
      apt:
        name: ['tmux', 'kdiff3', 'sublime-text']
        state: present
    - name: Ensure SQLite3 utilities are present
      become: yes
      apt:
        name: ['sqlite3', 'sqlitebrowser']
        state: present
    - name: Install Git Configurations
      template:
        src: templates/gitconfig.j2
        dest: /home/vagrant/.gitconfig
        owner: vagrant
        force: no
    - name: Ensure directory repos present
      file:
        path: '/home/vagrant/repos/python-hahow'
        state: directory
